### ISSUE TITLE
Use non breaking spaces between amount and symbol.

### ISSUE THREAD

**Issue by ZeHiro** [smirzaei/currency-formatter#15]
This prevents to have a new line between amount and symbol. As the lib is for dislay purpose, not for calculation purpose, it shouldn't be a problem for users.
Maybe an additional 'global setting' could be used.
Thanks for the lib btw.

**Comment by ZeHiro** [comment]
Could also be the case with spaces used for thousands separator

**Comment by smirzaei** [comment]
Hi,

I'm not exactly sure what you mean by "non breaking space". Do you want to remove all whitespace from the output? If so just removing the whitespace after the output is generated should be much easier.

Something like

```JAVASCRIPT
currencyFormatter.format(1000000, { code: 'EUR' }).replace(/ /g, '');
```

**Comment by ZeHiro** [comment]
Hi, 
I am talking about &nbsp; : https://en.wikipedia.org/wiki/Non-breaking_space
They are used to "stick" together the currency and the amount, but keeping the space in between. It is useful when you print the formatted price at the end of a line. The whole amount is put on a new line, in stead of separating the amount from currency. In some situations (using this library for website) I have : 
``` 
some text here 3 000 (end of line)
€
``` 
I would expect 
``` 
some text here (end of line)
3 000 €
```

**Comment by smirzaei** [comment]
Interesting, yeah it would be a good improvement! I guess if we use a non breaking space character  in `index.js`[[25](https://github.com/smirzaei/currency-formatter/blob/8656060b707d8b8c9461c7a7291d798a7c90bb9f/index.js#L25), [28](https://github.com/smirzaei/currency-formatter/blob/8656060b707d8b8c9461c7a7291d798a7c90bb9f/index.js#L28)] and every space character in the `currencies.js` like in line [401](https://github.com/smirzaei/currency-formatter/blob/8656060b707d8b8c9461c7a7291d798a7c90bb9f/currencies.js#L401), it should be enough.

Unfortunately I don't have much free time to experiment with this right now, but I'll definitely look into it! In the meantime a PR is very welcome :)

**Comment by ZeHiro** [comment]
I'll try to do something.

**Comment by smirzaei** [comment]
Thank you! :)

**Comment by ZeHiro** [comment]
in fact the non breaking space is already used for thousands separators
