### ISSUE TITLE
get rif of lodash dependency

### ISSUE THREAD

**Issue by ZeHiro** [smirzaei/currency-formatter#16]
The Array.prototype.find is part of ECMA 2015. Mozilla also provudes a polyfill for non supported browsers.
This will nake the library smaller. 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find

**Comment by smirzaei** [comment]
Yeah I'd like to get rid of that dependency as well. I wasn't very happy about this commit 852f10e4491dd96b9467a6e7c2186df293da2701, a polyfill sounds way better.
