### ISSUE TITLE
CHF Symbol should be CHF.

### ISSUE THREAD

**Issue by sahanDissanayake** [smirzaei/currency-formatter#19]
@smirzaei

**Comment by smirzaei** [comment]
#18

**Comment by sahanDissanayake** [comment]
Will u publish on NPM soon ? thanks

**Comment by smirzaei** [comment]
Yeah I just did, I think it'll take a few minutes for it to pick it up.

**Comment by sahanDissanayake** [comment]
I think we may have to look in to this http://www.mcdonalds.ch/de/menukarte/menus/caesar-salad-grilled-chicken-menu 👍
