### ISSUE TITLE
Space between number and symbol

### ISSUE THREAD

**Issue by sahanDissanayake** [smirzaei/currency-formatter#21]
If the symbol is on right and the space is added, should the space be added to the left of the symbol ?

`12.20CHF should be 12.20 CHF` ?

**Comment by sahanDissanayake** [comment]
My bad, this is working !!!

**Comment by smirzaei** [comment]
The space is always between the symbol and the value.
https://github.com/smirzaei/currency-formatter/blob/205711e0734ee90b183c6d8f43afcf52f33268a5/test.js#L91-L116

**Comment by sahanDissanayake** [comment]
Yeah sorry, Did the test.js after issue was created..

**Comment by smirzaei** [comment]
Glad it's working now :)
