### ISSUE TITLE
Commas for currency code 'INR'

### ISSUE THREAD

**Issue by cfkenandy** [smirzaei/currency-formatter#22]
var number = 123456.789;
currencyFormatter.format(123456.789, { code: 'INR' });
 // this displays, "123,456.79₹" but should be, "1,23,456.789₹". 

Is there a setting to adjust commas?

**Comment by smirzaei** [comment]
Interesting issue... We are using [accounting.js](https://github.com/openexchangerates/accounting.js) to do the formatting for us, and I've been looking at their documentation and looks like there is no way for us to do this.

Checkout `accounting.formatMoney()` http://openexchangerates.github.io/accounting.js/#documentation

Right now, I can't think of a good and clean solution for this issue. You might have a better luck reaching out to them and see if there is a way which we can control how the thousand separators are placed.

**Comment by cfkenandy** [comment]
ok, will reach out to them. thanks!
