### ISSUE TITLE
Negative values are not correctly handled

### ISSUE THREAD

**Issue by zkhalapyan** [smirzaei/currency-formatter#24]
Seems like the formatter doesn't handle negative values, below example prints out "$-10.00".

```
var currencyFormatter = require('currency-formatter');
console.log(currencyFormatter.format(-10.0, { code: 'USD' })); // prints $-10.00
```

Is there an option that I will need to set or negative values are not supported?

**Comment by smirzaei** [comment]
Interesting... I'll look into it.
Just to make sure, we should show it like `($10.00)` instead of `$-10.00` right?

**Comment by ZeHiro** [comment]
@smirzaei I think this should be "-$10.00".
https://answers.yahoo.com/question/index?qid=20080220214302AA2N8kn

For sure, in Euro you would write "-10,00 €"

**Comment by smirzaei** [comment]
Yeah I looked around and looks like both `($10)` and `-$10` are common.

http://ux.stackexchange.com/questions/1869/preferred-format-to-display-negative-currency-us-english

I'm going to add an option to allow the user to pick which format they want to use, but the question is which one should be the default?

**Comment by smirzaei** [comment]
The best case scenario would be to pick the right format based on the user's locale. I checked how Java's `NumberFormat` acts in this situation and this is the result:

```SCALA
scala> println(NumberFormat.getCurrencyInstance(new Locale("en", "US")).format(-123))
($123.00)

scala> println(NumberFormat.getCurrencyInstance(new Locale("en", "GB")).format(-123))
-£123.00

scala> println(NumberFormat.getCurrencyInstance(new Locale("en", "CA")).format(-123))
-$123.00
```

But unfortunately we don't have this kind of data.

**Comment by smirzaei** [comment]
And the accounting library which we use to do the formatting. That's why the current version is displaying something like `$-10` right now.

https://github.com/openexchangerates/accounting.js/blob/15e38ac6d61460958c389cc319a837e7a0d6cfa7/tests/jasmine/core/formatMoneySpec.js#L11-L17

**Comment by smirzaei** [comment]
PR: #25

I published a new version to NPM. Let me know if you're having any issues. :)
