### ISSUE TITLE
1.0.5 error when formatting 0 value

### ISSUE THREAD

**Issue by MarcDiprose67** [smirzaei/currency-formatter#26]
Hi, my app failed upon update today, it seems due to upgrading to 1.0.5 - when I call 

currencyFormatter.format(0, 'GBP')

I get the type error of cannot find 'replace' of undefined.

Rolled back to 1.0.4 and it is fine

**Comment by smirzaei** [comment]
Thanks for reporting this, I'll publish a new version with the fix soon.

**Comment by smirzaei** [comment]
Published a new version and we have tests for zero values so it wouldn't happen again :p

https://github.com/smirzaei/currency-formatter/blob/d87755c55beb19ac941282d58d17ae64d9d04d9a/test.js#L14-L17
