### ISSUE TITLE
EUR symbolOnLeft per country

### ISSUE THREAD

**Issue by edorivai** [smirzaei/currency-formatter#29]
Very useful library, thanks for sharing!

So this is a major pain in the ass, and not specific to this library at all, but placement of the euro sign (€) differs between countries.

[Quote](https://web.archive.org/web/20100218184700/http://www.delidn.ec.europa.eu/en/references/references_5.htm#Q12) from the European commission:

> **Where should the euro symbol be placed: ‘€ 100’ or ‘100 €’?**
> There are no official standards on where to place the euro symbol. In English text, the usual practice is to place the symbol "€" before the amount in figures, i.e. € 100. In French text, the symbol is usually placed after the amount in figures, i.e. 100 €.

The app I'm working on requires correct placement across locales, so for example, our Dutch version should display `€100`, while the French version should display `100 €`.

Currently we maintain our own list of currencies per country, which means that we have two "versions" of the euro, one with `symbolOnLeft=true` and the other one with `symbolOnLeft=false`. I can hardly imagine we're the only ones struggling with this, and this library might be a nice central place to solve this issue.

Would love to hear your thoughts!

**Comment by edorivai** [comment]
Dove into it a bit more, and found the problem to be even more complex :tada: 

Take a look at this table: http://www.evertype.com/standards/euro/formats.html

It shows a couple different Euro formats:
1.234,56 €
1 234,56 €
€1.234,56
€1,234.56

Note that not only location of the sign differs, but the separators (`.`, `,`, ` `) differ as well.

**Comment by smirzaei** [comment]
I see, and I agree how this can be a problem. I'll try to do some experiments after work.

We'd need to take locale as a parameter and use it for formatting, but our data structure won't really allow this, we'd need to duplicate the data which is not ideal.

There is another way, which I've seen in Java and .NET world, for example Java has a class called `NumberFormat` which takes a locale and formats the number or currency based on that locale but that approach also might not be ideal, here's an example

```
scala> NumberFormat.getCurrencyInstance(new Locale("en", "US")).format(1234.56)
res0: String = $1,234.56

scala> NumberFormat.getCurrencyInstance(new Locale("it", "IT")).format(1234.56)
res1: String = € 1.234,56

scala> NumberFormat.getCurrencyInstance(new Locale("fr", "FR")).format(1234.56)
res2: String = 1 234,56 €

scala> NumberFormat.getCurrencyInstance(new Locale("en", "GB")).format(1234.56)
res3: String = £1,234.56
```

This is great but it's only ideal if you first convert the price to the target currency.

I've been down that road and believe me I know your pain :p but to be honest I don't think there is a one size fit all solution here, it depends on your application and how you want to handle localization. I created this library to have something quick to show the currency in the way it's mostly represented (usually the english version of Wikipedia)

Anyways if you have any suggestions, I'm all ears :)

**Comment by edorivai** [comment]
I have a couple of suggestions!

First off, I checked the ECMAscript [Intl](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NumberFormat#Examples) api, which allows you to do this:

```js
new Intl.NumberFormat('nl-NL', { style: 'currency', currency: 'EUR' }).format(1234.6789);
// '€ 1.234,68'
new Intl.NumberFormat('de-DE', { style: 'currency', currency: 'EUR' }).format(1234.6789);
// '1.234,68 €'
```

Which looks awesome, and might be the ideal way to do it. Except that it turns out that not all browsers format all currencies the same for all locales. For example, I found that Firefox currently wrongly renders the euro sign before the amount for `de-AT`. And the Intl API does not support any way of overwriting the formatting.

Some of the reasons in favor of having a user-land package for currency rendering I can think of are:

- Having predictable formatting across environments
- Being able to override certain formats if this is required for your specific use-case
- Having a shorter iteration cycle for fixing formats

If you're open for it, I'll start working on a locale-based implementation, and submit a PR.

**Comment by edorivai** [comment]
See #30 for suggestions and a first attempt to an implementation.

**Comment by smirzaei** [comment]
Excellent find, I didn't know about `Intl` API.

Either way you are more than welcome to extend this library, as long as it's backwards compatible and efficient :)

For this case I think allowing user to pass the locale as an optional parameter would be ideal, something like

```JS
currencyFormatter.format(1000000, { code: 'EUR', locale: 'nl-NL' })
```

Sorry I can't be much of help, have a ton to do at work these days.

Let me know if you have any questions :)

**Comment by smirzaei** [comment]
For some reason didn't see the PR, I'll check it out soon.

**Comment by smirzaei** [comment]
#30
