### ISSUE TITLE
One export per currency?

### ISSUE THREAD

**Issue by oncletom** [smirzaei/currency-formatter#34]
It happens that including all the currencies adds up 30K in a webpage (against ~2K for the lib itself).
It is useful when the currency value is dynamic and not predictable.

Although in some (many?) cases, the list of currencies is deterministic. When you use only one or two currencies, the cost of including the lib should not be higher than 3KB.

```js
import formatEUR from 'currency-formatter/EUR'

formatEUR(30.9); // --> '30,90€'
```

Internally, it means that `currency-formatter/EUR.js` could look like:

```js
import currency from '../currencies/EUR.json';
import format from '../index.js';

const formatCurrency = format.bind(null, currency);

export default formatCurrency;
```

By extent, maybe the first and last argument could be swapped to allow partial application, which is also a good way to support a functional approach:

```js
import format from 'currency-formatter';
const formatEUR = format.bind(null, { currency: 'EUR' });

formatEUR(30.9); // --> '30,90€'
```

#PossiblyOverEngineering

cc @davidbruant

**Comment by smirzaei** [comment]
I really like this idea! A little while ago I was thinking about restructuring this library (maybe a complete rewrite with a major version bump?)


```
/index.js --> Core functionality?
/currencies/index.js --> Iterate over each directory and load all the data (useful when the currency is dynamic)
/currencies/USD/USD.json --> Currency data
/currencies/USD/index.js --> The format function?
/currencies/EUR/EUR.json
/currencies/EUR/index.js
...

/locales/en-US/en-US.json --> Locale specific data
/locales/en-US/index.js --> The format function
...
```

I think it's pretty much what you're suggesting, but I really don't know if we can use the node's file APIs or how can we also have a ES5 compatible version.

/discuss

**Comment by oncletom** [comment]
Yeah I guess if you make `index.js` being the core function which expects to be passed a fully formatted object (that you require/import or write manually), it would simplify a lot of stuff. No need for a `:currency/index.js` file this way.

```js
import { currency, format }  from 'currency-formatter';
import EUR from 'currency-formatter/EUR';

const formatEUR = currency(EUR);

// both next are the same
format(30.9, EUR);
formatEUR(30.9);
```

All currencies could be available for people having to deal with a lot of them:

```js
import format  from 'currency-formatter';
import { EUR, USD } from 'currency-formatter/currencies';

format(30.9, EUR);
format(30.9, USD);
```

**Comment by DavidBruant** [comment]
> but I really don't know if we can use the node's file APIs or how can we also have a ES5 compatible version.

I'm not sure I follow the consideration of the file API.
In any case, if you want to publish an NPM package that is available both in ES5 and ES6 format, I think what you need to do is:
* Have your source code in ES6 (at least the module syntax)
* Use the [prepublish lifecycle script](https://docs.npmjs.com/misc/scripts) to generate the ES5/CommonJS version (you can use Babel for the conversion)
* Add a [`module` field to your package.json](https://github.com/rollup/rollup/wiki/pkg.module) so bundlers like rollup can decide to not include unused-currencies code.
* Publish

**Comment by DavidBruant** [comment]
> I'm not sure I understand the consideration of the file API. Why would it be needed?

ok, I get it

> /currencies/index.js --> Iterate over each directory and load all the data (useful when the currency is dynamic)

I think you'll need to do it manually like d3.js does:
https://github.com/d3/d3/blob/master/index.js

or of course, you can have a build tool that generates this for you. This build tool will use the file API

**Comment by oncletom** [comment]
+1 on what @DavidBruant just wrote – if it is not manual, it has to be generated in a way which makes currencies exports static and _pure_.

**Comment by smirzaei** [comment]
I see... Yeah having a build file makes sense. I'll read up on the `module` field in package.json to see how it's used.

But even though these changes don't seem to be that time consuming, I don't think I'm going to find the free time to make these changes for at least a month. (I'll try to though, these changes sound really interesting!) Of course if you can you are more than welcome to to send a PR. :smile:

Thanks for the suggestion and the detailed explanation 👍

**Comment by edorivai** [comment]
Sorry I'm late, but thought I'd chime in a bit. I think a nice way to do it would be something similar to how react-intl does it:

```js
import {addLocaleData} from 'react-intl';
import en from 'react-intl/locale-data/en';
import fr from 'react-intl/locale-data/fr';
import es from 'react-intl/locale-data/es';

addLocaleData([...en, ...fr, ...es]);
```
I'm seeing this pattern in more places (moment.js for example). This allows for bundlers (like webpack) to only include the locale specific files that are required. In addition to this mechanism, having a main file that includes all languages is useful in cases that bundle size in not super important, like on the server.

With the addition of locale based formatting, we have a complication though. How will we structure the data? Should users include currencies and locale-based formatting data separately? This would give the most control, but might also be confusing; formatting for `{ locale: nl-NL }` would now require importing both the `nl-NL` locale format, as well as the `EUR` currency.

Some food for thought :)

**Comment by smirzaei** [comment]
I haven't had much time to think about this #StartupLife but overall I think this could work.

File structure:

```
```

**Comment by smirzaei** [comment]
I haven't had much time to think about this #StartupLife but overall I think this could work.

File structure:

```
/currencies/USD.json --> Currency data
/currencies/EUR.json
/currencies/index.js -->Sum of all currency data for when the currency is unknown beforehand (created at build time)
...

Similar pattern for locales
/locales/en-US.json --> Locale specific data
/locales/en-GB.json
/locales/index.js
...
```

Usage when the currency is known before hand

```JS
import { format } from 'currency-formatter'
import USD from 'currency-formatter/currencies/USD'
import en_US from 'currency-formatter/locales/en-US'

const customUserOverrides = { symbolOnLeft: false }

format(1234, USD, en_US, customUserOverrides)
```

Usage when the currency is dynamic

```JS
import { format } from 'currency-formatter'
import currencies from 'currency-formatter/currencies'
import locales from 'currency-formatter/locales'

const customUserOverrides = { symbolOnLeft: false }

format(1234, currencies['USD'], locales['en-US'], customUserOverrides)
```

Both locales and custom overrides objects are optional and they just override the fields from the previous objects. Similar to how object assign works.

Let me know if it makes sense and @edorivai if it's close to the pattern that people are using these days :)

**Comment by edorivai** [comment]
I mean, in broad strokes your approach is similar to what I see used in big libraries. But what I like about the react-intl approach is that you can do a one-time setup of the locales that you will need, and afterwards don't need to think about importing them any more.

I like the current API `format(1234, { locale: 'en-GB' })` or `format(1234, { code: 'GBP' })`, and we could keep that simplicity, but we'd need to accommodate this "setup" like feature. Something like:

```js
import { format, addCurrencies, addLocales } from 'currency-formatter'
import USD from 'currency-formatter/currencies/USD'
import GBP from 'currency-formatter/currencies/GBP'
import en_US from 'currency-formatter/locales/en-US'

// These would add the currencies and locales globally
addCurrencies(USD, GBP);
addLocales(en_US);

const customUserOverrides = { symbolOnLeft: false }

// Because the currencies and locales have been added, we can use the current API
format(1234, { code: 'GBP', locale: 'en-US' }, customUserOverrides)
```

This pattern is especially useful in larger apps, where you have a one-time setup, and any deeply nested components only have to specify the locale.

Actually, I'm just now coming up with this, but in my case it would even be useful to globally set the locale or currency default. I'm working on a site that is translated to several locales with varying currencies, but one user typically only ever needs a single currency (the one corresponding to her locale of choice). It would be very useful to be able to set the locale once, and let deeply nested components just render:

```js
// At startup
formatCurrency.setLocale('nl-NL')

// Somewhere deep in my app
format(myPrice)
```

This is also how I use moment.js:

```js
// At startup
moment.locale('nl-NL')

// Somewhere deep down
moment().format('LLL') // 29 maart 2017 16:06
```
