### ISSUE TITLE
Possible to retrieve the unformatted version?

### ISSUE THREAD

**Issue by brandondurham** [smirzaei/currency-formatter#36]
If I have the string `$2,000.00` that was formatted by currency-formatter, is it possible to _remove_ formatting and return it to a pure Number?

In this instance I would love to return `2000.00`.

**Comment by smirzaei** [comment]
No, sorry. Formatting is only one-way at the moment, but having a parsing feature sounds interesting.

**Comment by edorivai** [comment]
Did you look at `accounting.unformat`?

```js
// Standard usage and parameters (returns number):
accounting.unformat(string, [decimal]);

// Example usage:
accounting.unformat("GBP £ 12,345,678.90"); // 12345678.9

// If a non-standard decimal separator was used (eg. a comma) unformat() will need it in order to work out
// which part of the number is a decimal/float:
accounting.unformat("€ 1.000.000,00", ","); // 1000000
```

**Comment by smirzaei** [comment]
We now have this feature. Thanks to #44 and #42 

Check out the readme for the documentation :) (https://github.com/smirzaei/currency-formatter/commit/43db0c103b0ac1c4a4b9e36518b2523e1ec5798d)
