### ISSUE TITLE
expose accounting.unformat function

### ISSUE THREAD

**Issue by burrack** [smirzaei/currency-formatter#42]
Hey :)

It would be nice to have the accounting.unformat function here.
I don't want to import your lib and import your library your are using

**Comment by edorivai** [comment]
Just FYI, if you import a version of accounting that is compatible with the version that we require in currency-formatter, npm (or yarn) will probably share the dependency. So you wouldn't have any extra code in your project.

**Comment by burrack** [comment]
you right :) you can close this

**Comment by davidmpaz** [comment]
Hi,

why close it? I think the initial idea is legitimate and provides value. 

Could this be built on this library? 

cheers

**Comment by edorivai** [comment]
I think you could just do

```js
import accounting from 'accounting';

accounting.unformat("£ 12,345,678.90 GBP"); // 12345678.9
```

No need for this library to expose it, right?

**Comment by davidmpaz** [comment]
You are right, but ... 

would not make it better if we have a facade on this module like we have in `format`?

I think it would even look more natural, to offer both posibilites (read/write) a number as money. I was thinking in the value added by currencies data in here. Maybe the right question now would be:

What value does this module add for using it and not just do: 
`accounting.formatMoney(4999.99, "€", 2, ".", ","); // €4.999,99` ?

Doesn't apply the same to the `unformat` function?

Also what if we have only: `£ 12,345,678.90` and the localization data is coming from other places as options or so? then, concatenate strings to get desired format?

Does all this make sense? maybe i am over engineering things :), after all what we want here is to get a number from an string representing a number. But in my small tries I did found not so trivial to use `accounting.unformat`.

**Comment by edorivai** [comment]
I'm not sure I correctly understand your point.

Perhaps this is useful, I see it as follows:

> What value does this module add

The value added of this module is in its formatting data. It provides consistent formatting given a certain currency or locale.

Two alternatives and their issues:

1. `accounting`. You'll have to provide the currency symbol, separators, and decimal count yourself.
2. browser native `Intl` API. As far as I know, browsers render currencies inconsistently. Specifically, not all browser correctly render euro amounts. (Some place the symbol wrongly, position depends on country; €14 for NL, 14€ for DE)

**Comment by davidmpaz** [comment]
Indeed is useful,

lets try to continue from these ideas and lets ask now: 

Does something of what you explained apply the same to the `unformat` function?

Is there any possible kind of improvement to: `accounting.unformat("£ 12,345,678.90 GBP")`

What if I have only this as input: `"2550,00"`? This could be many things depending of the locale, my point was that, one level more of abstraction could provide the right (or at least easier) API to use when parsing an string representing a money amount.

This `"2550,00"` by itself means nothing, we still need the locale info, but using `accounting` I would need to start concatenating string and so on, instead passing an object of options to the function like in `format` is done for example.

Does make more sense now?  Many thanks for taking the time to explain the ideas.

Regards

**Comment by edorivai** [comment]
Ah! I totally get your point now!

I actually dove into it a little bit more, and it turns out that `accounting.formatting` doesn't ready any of the currency information from the input string. It just strips it, and assumes the default decimal character, unless you explicitly specify it:

```js
accounting.unformat('10,000 CHF') // 10000
```
...which I'm pretty sure should be 10, given that the Suisse used the comma as the decimal separator.

Accounting allows for passing the decimal separator as a second argument:
```js
accounting.unformat('10,000 CHF', ',') // 10, yay
```
And I guess this is what you mean; we could fetch the decimal separator from the currency or locale settings.

Would you be willing to submit a PR for this?

**Comment by davidmpaz** [comment]
Hi

thanks for coming back. Currently I have no time. I can try to get it done but I think it will take time for me right now, since I would need to read the current API and then workout the solution. No earlier than in two or three weeks. Sorry :(

For now, since we are already in same page, lets keep this open then

Regards

**Comment by edorivai** [comment]
@z0mt3c implemented it :) Thanks again.

**Comment by edorivai** [comment]
@smirzaei could you cut a minor release to npm? :smile:

**Comment by smirzaei** [comment]
Thanks for the help and sorry I wasn't around for this.

I'll update npm in a few mins :)

**Comment by davidmpaz** [comment]
Hi guys,

thanks for taking care of this. Please @smirzaei or @z0mt3c can the docs get updated to know how to use the new functionality. 

We can always look at code, but is better to have it in README.

thanks again!!
cheers

**Comment by smirzaei** [comment]
Thanks everyone for taking care of this. I updated the readme with the unformat docs.

I guess we can close this.
