### ISSUE TITLE
German Local wrong

### ISSUE THREAD

**Issue by MMueller86** [smirzaei/currency-formatter#45]
Hi,

the german local should also use the point as a thousand seperator. But the implementation is only showing a blank.

As a workaround I am using the netherland locale... 
(Both should be the same)

Current Implementation of 1,000,000.00: --> 1 000 000,00 €
Correct german usage: 1.000.000,00 €

With kind regards!

**Comment by smirzaei** [comment]
Thanks for letting us know.
I added the `de-DE` locale based on your description. Let me know if it's not right or feel free to modify the [locale data](https://github.com/smirzaei/currency-formatter/blob/6cf0e4616c2bee79f6d28fca02695acdf9434034/localeFormats.json#L51-L57) and send us a PR :)

Cheers

**Comment by MMueller86** [comment]
Thanks, it is working!
(only the doc on the mainpage is not anymore up2date)

cheers

**Comment by smirzaei** [comment]
Yeah you are right 😅, I'll take care of it.
