### ISSUE TITLE
Can not override formatting options i.e symbolOnLeft, spaceBetweenSymbolAndNumber etc.

### ISSUE THREAD

**Issue by sumitnitsurat** [smirzaei/currency-formatter#46]
I want to override the default setting for a currency so that I can provide space between symbol and number while setting the currency as USD. currency it comes from the currencies.json file and we can not override it.

**Comment by EmirGluhbegovic** [comment]
I am also looking for a way to add a space between the currency symbol and the the value.

**Comment by smirzaei** [comment]
You can override format pattern like this
```JS
currencyFormatter.format(1000000, { code: 'USD', format: '%s %v' }) //%s is the symbol and %v is the value
```

Let me know if it doesn't work for you.

**Comment by EmirGluhbegovic** [comment]
@smirzaei Thank you! That command works.

**Comment by smirzaei** [comment]
I'm glad. Looks like this is resolved then.

**Comment by EmirGluhbegovic** [comment]
Would suggest to update this on the read-me or somewhere so its easier to find.
