### ISSUE TITLE
option decimal in format function

### ISSUE THREAD

**Issue by aayushis12** [smirzaei/currency-formatter#51]
Version used: 
"currency-formatter": "^1.3.2"

My function accepts a number and changes it to USD. Since I don't want decimal values, so I have specified the decimal option as zero.
`
export default (amount) => {
	return currencyFormatter.format(20,{code: currency, decimal: 0});
}`

The expected output should be $20
But the output comes as $20000

Similarly, if I write the code like this
`
export default (amount) => {
	return currencyFormatter.format(20,{code: currency, decimal: 1});
}`
The result comes as ---- $20100

**Comment by edorivai** [comment]
`decimal` is used to specify the decimal separator, which is usually a comma `,` or a dot `.`. You probably want `decimalDigits`:

```js
export default (amount) => currencyFormatter.format(20,{code: currency, decimalDigits: 0});
```

**Comment by aayushis12** [comment]
but why is decimal:0 adding extra zeroes to my number?

**Comment by aayushis12** [comment]
Thanks @edorivai . I solved it using precision `export default (amount) => currencyFormatter.format(20,{code: currency, precision: 0});`
