### ISSUE TITLE
Rounding Off issue

### ISSUE THREAD

**Issue by sanyamagrawal** [smirzaei/currency-formatter#58]
Is there a reason for the library to convert
currencyFormatter.format(0.999, { code: 'EUR'})

shows "1,00 €"

Is there a reason for this rounding off, and also is there a way to avoid this rounding off ?

**Comment by smirzaei** [comment]
It's because the precision is set to 2 by default for `EUR`. You can get around it by manually setting the `precision` property.

For example:

```JS
currencyFormatter.format(0.999, { code: 'EUR', precision: 3 })
```

Returns

```
"0,999 €"
```
