### ISSUE TITLE
support 0 decimal digits

### ISSUE THREAD

**Issue by jonathanong** [smirzaei/currency-formatter#6]
https://github.com/smirzaei/currency-formatter/blob/c5bebdb2bbef189d42f081cff5f5acc71db78b0f/index.js#L37

should be:

```js
precision: typeof options.precision === 'number' ? options.precision : currency.decimalDigits
```

and the same with the other options

**Comment by smirzaei** [comment]
Good catch... again :grin: and thanks. Let me know if I missed something.
