### ISSUE TITLE
1.4.3 error when formatting 0 value

### ISSUE THREAD

**Issue by ManuMorenoGonzalez** [smirzaei/currency-formatter#60]
Version used:
"currency-formatter": "^1.4.3"

Hello, I would like to report about a bug. When I try to change the currency of the value 0, the result is **undefined**.
consolecurrencyFormatter.format(0, { locale: 'en-US' });
//=> undefined

When should be for example: 
consolecurrencyFormatter.format(0, { locale: 'en-US' });
// => '$0'
consolecurrencyFormatter.format(0, { locale: 'de-DE' });
//=> '0 €'

Thank you so much.

**Comment by smirzaei** [comment]
I can't reproduce it. This is what I'm getting:

https://runkit.com/embed/udaibyot0bse

**Comment by ManuMorenoGonzalez** [comment]
Thank you so much, it is working to me now :)
