### ISSUE TITLE
Global option for no decimal places?

### ISSUE THREAD

**Issue by aaronjpitts** [smirzaei/currency-formatter#7]
Hi, great script!

It would be useful to be able to set global options for each currency such as to not use a decimal place. Is this possible?

Many thanks

**Comment by smirzaei** [comment]
Hi,

Do you mean something like this?
https://github.com/smirzaei/currency-formatter/blob/master/test.js#L143-L150

**Comment by sahanDissanayake** [comment]
I think @smirzaei found the answer :)

**Comment by sahanDissanayake** [comment]
That seems to just take the DOT . off ?!?!?

**Comment by sahanDissanayake** [comment]
@smirzaei The issue is about REMOVING decimals I think.

So if the number is 10, then if it is formatted with USD you would normally get $10.00 and if someone set decimal to '' then you would expect the format to comeout just $10 ?

**Comment by sahanDissanayake** [comment]
@aaronjpitts 

Maybe you need
```
var result = currencyFormatter.format(1000000, {
        code: 'USD',
        precision: 0
      })
```

**Comment by smirzaei** [comment]
Exactly, if you don't want the decimal points you can set the `precision` to 0.
I'm going to close this issue since it's been inactive for months.
