### ISSUE TITLE
currency symbols

### ISSUE THREAD

**Issue by talgautb** [smirzaei/currency-formatter#8]
Hi! good utility!
You have some mistakes, for example symbol of `KZT`.
I have [database of currency](https://github.com/talgautb/typographic-currency-db) (only official symbols)
You can just take it or use plugin. Also i can send PR after couple of days.

**Comment by smirzaei** [comment]
Thanks for pointing it out, I got the data from someone in the company and still waiting for them to tell me where they got it from!

I think the best approach would be to update the symbols in the [currencies.js](https://github.com/smirzaei/currency-formatter/blob/3c224cbe1afd793f31b9d7e6b6eccc9c80317f04/currencies.js) file with the symbols from your repository.

I'm swamped at work these days so it might take a few days for me to get to it, and a PR would be really awesome!

**Comment by talgautb** [comment]
#11
